###
POST http://127.0.0.1:8081/member/register
Content-Type: application/json

{
    "username": "cyhfvg2",
    "password": "password"
}

###
POST http://127.0.0.1:8081/member/login
Content-Type: application/json

{
    "username": "cyhfvg",
    "password": "password"
}

###
POST http://127.0.0.1:8081/member/login
Content-Type: application/json

{
    "username": "shabulaji",
    "password": "shabulaji"
}
