### 管理员登录
GET http://localhost:8080/bookMarket-java/umsAdmin/login
Content-Type: application/json

{
    "username": "adminTest1",
    "password": "123456*hhd"
}

###
GET http://localhost:8080/bookMarket-java/umsAdmin/login
Content-Type: application/json

{
    "username": "adminTest1",
    "password": "123456"
}

###
