### 管理员登录
GET http://localhost:8080/bookMarket-java/umsAdmin/login?adminName=adminTest1&password=123456*hhd
Content-Type: application/json

###
GET http://localhost:8080/bookMarket-java/umsAdmin/login
Content-Type: application/json

{
    "adminName": "adminTest1",
    "password": "123456*hhd"
}

###
